# Generated by Django 6.0.4 on 2026-04-19 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('SALLE_ELECTRONIC', 'Salle Electronic'), ('SALLE_MECANIC', 'Salle Mecanic'), ('BUREAU_3D', "Bureaux pour l'impression 3D"), ('BUREAU_CC', 'Bureaux pour CC')], max_length=50)),
                ('activity', models.TextField()),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
