# Generated by Django 6.0.4 on 2026-04-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_labsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labsession',
            name='location',
            field=models.CharField(choices=[('SALLE_ELECTRONIC', 'Salle Electronic'), ('SALLE_MECANIC', 'Salle Mecanic'), ('SALLE_MAINTENANCE', 'Salle Maintenance'), ('BUREAU_3D', "Bureaux pour l'impression 3D"), ('BUREAU_CC', 'Bureaux pour CC')], max_length=50),
        ),
    ]
